[package]
name = "ishtarx"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
ratatui = "0.29.0"
tree-sitter = "0.24.4"
tree-sitter-highlight = "0.24.4"
tree-sitter-javascript = "0.23.1"
unicode-normalization = "0.1.24"

